/*************************************************************************************************************
 * Module: Ultrasonic Sensor
 * File Name: ultrasonic.c
 * Description: Ultrasonic Sensor driver Source file
 * Author: Youssef Zaki
 ************************************************************************************************************/

#include "ultrasonic.h"
#include "icu.h"
#include "gpio.h"
#include <util/delay.h>

uint8 g_edgeCount = 0;
uint16 time = 0;

/*
 * DESCRIPTION:
 * 1. Initialize the ICU driver as required.
 * 2. Setup the ICU call back function.
 * 3. Setup the direction for the trigger pin as output pin through the GPIO driver.
 */
void Ultrasonic_init(void)
{
	/* Create configuration structure for ICU driver (F_CPU/8, Rising Edge) */
	Icu_ConfigType Icu_Config = {F_CPU_8,RISING};

	/* Initialize the ICU */
	Icu_init(&Icu_Config);

	/* Set the Call back function pointer in the ICU driver */
	Icu_setCallBack(Ultrasonic_edgeProcessing);

	/* Setup of the Trigger pin as output pin */
	GPIO_setupPinDirection(TRIGGER_PORT_ID,TRIGGER_PIN_ID,PIN_OUTPUT);
	/* Ensure that trigger pin is low at beginning */
	GPIO_writePin(TRIGGER_PORT_ID,TRIGGER_PIN_ID,LOGIC_LOW);
}

/*
 * DESCRIPTION:
 * Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void)
{
	/* Triggering the pulse to the ultrasonic */
	GPIO_writePin(TRIGGER_PORT_ID,TRIGGER_PIN_ID,LOGIC_HIGH);
	_delay_us(10); /* transmit trigger pulse of at least 10 us to the HC-SR04 Trigger Pin */
	GPIO_writePin(TRIGGER_PORT_ID,TRIGGER_PIN_ID,LOGIC_LOW);
}

/*
 * DESCRIPTION:
 * 1. Send the trigger pulse by using Ultrasonic_Trigger function.
 * 2. Start the measurements by the ICU from this moment.
 * 3. Return The measured distance in Centimeter.
 */
uint16 Ultrasonic_readDistance(void)
{
	/* Sending the trigger pulse by using Ultrasonic_Trigger function */
	Ultrasonic_Trigger();

	return (time/(58.8)); /* calculating distance in cm */
}

/*
 * DESCRIPTION:
 * This is the call back function called by the ICU driver.
 * This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void)
{
	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		Icu_clearTimerValue();
		/* Detect falling edge */
		Icu_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		/* Store the High time value */
		time = Icu_getInputCaptureValue();
		/* Clear the timer counter register to start measurements again */
		Icu_clearTimerValue();
		g_edgeCount=0;
		/* Detect rising edge */
		Icu_setEdgeDetectionType(RISING);
	}
}
